name: Deploy To AWS S3
description: Deploy SPA To S3
inputs:
  bucket:
    description: "S3 bucket name"
    required: true
  bucket-region:
    description: S3 bucket region
    required: false
    default: us-east-1
  build-folder:
    description: The build deployable files
    required: true
runs:
  using: "node16"
  main: main.js
